name: CI

on:
  workflow_call:

jobs:

  check_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: ./.venv
        key: venv-${{ github.run_id }}

    - name: Touch dev environment
      run: make touch-dev
          
    - name: Check format
      run: make check-format

    - name: Run pylint
      run: make lint
      
    - name: Check typing
      run: make check-typing
