name: Init

on:
  workflow_call:

jobs:

  init_dev:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ github.run_id }}

      - name: Init dev environment
        run: make dev